usr/lib/llvm-3.5/include/clang
usr/lib/llvm-3.5/include/clang-c
usr/lib/llvm-3.5/lib/libclang*a
usr/lib/llvm-3.5/lib/libclang-3.5.so

usr/lib/llvm-3.5/lib/libmodernizeCore.a

build-llvm/tools/clang/runtime/compiler-rt/clang_linux/ usr/lib/llvm-3.5/lib/clang/3.5/lib/

#usr/include/clang                  /usr/include/
#usr/include/clang-c                /usr/include/
#usr/lib/libclang.so                /usr/lib/
#usr/lib/libclang*a                 /usr/lib/
