usr/lib/llvm-3.5/lib/libLLVM*.a
usr/lib/llvm-3.5/lib/libllvm*.a
usr/lib/llvm-3.5/lib/LLVM*.so
usr/lib/llvm-3.5/lib/libLTO.*
usr/lib/llvm-3.5/lib/BugpointPasses.so
usr/lib/llvm-3.5/include/llvm/      usr/include/llvm-3.5/
usr/lib/llvm-3.5/include/llvm-c/	usr/include/llvm-c-3.5/
# Explicit debian/tmp since there are multiple declarations
debian/tmp/usr/lib/llvm-3.5/share/llvm/cmake/*.cmake usr/share/llvm-3.5/cmake/

build-llvm/Makefile.common		/usr/lib/llvm-3.5/build/
build-llvm/Makefile.config		/usr/lib/llvm-3.5/build/
build-llvm/config.status		/usr/lib/llvm-3.5/build/
Makefile.rules			        /usr/lib/llvm-3.5/build/
configure			            /usr/lib/llvm-3.5/build/
autoconf/			            /usr/lib/llvm-3.5/build/

utils/vim/llvm-3.5.vim		        usr/share/vim/addons/syntax/
utils/vim/tablegen-3.5.vim		    usr/share/vim/addons/syntax/

utils/emacs/emacs.el		    usr/share/emacs/site-lisp/llvm-3.5/
utils/emacs/llvm-mode.el	    usr/share/emacs/site-lisp/llvm-3.5/
utils/emacs/tablegen-mode.el	usr/share/emacs/site-lisp/llvm-3.5/

