#!/bin/sh -e

if test "$1" = "remove"; then
    if test -x /usr/sbin/update-binfmts; then
        update-binfmts --package llvm-3.5-runtime \
            --remove llvm-3.5-runtime.binfmt /usr/bin/lli-3.5 || true
        if test -f /var/lib/binfmts/llvm-3.5.binfmt; then
            # Purge old file
            update-binfmts --package llvm-3.5-runtime \
                --remove llvm-3.5.binfmt /usr/bin/lli-3.5 || true
        fi
    fi
fi

#DEBHELPER#

